print("Hello. I am your teacher for today. Are you ready to learn?")
print("What is your name?")
name = input()
print("Hello " + name + ".")
print("What subject would you like to learn about today?")
subject = input()
print("Fantastic choice! " + subject + " is a very interesting subject.")
print("Which part of " + subject + " Interests you the most?")
interest = input()
print("Okay, " + name + ". Let's learn about " + subject + ". And more specifically " + interest + ".")